# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.CharField(max_length=10000, verbose_name='内容')),
                ('creationTime', models.DateTimeField(auto_now_add=True, verbose_name='保存日期')),
                ('changeTime', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('readTimes', models.IntegerField(verbose_name='阅读次数')),
                ('goodTimes', models.IntegerField(verbose_name='点赞次数')),
                ('badTimes', models.IntegerField(verbose_name='点踩次数')),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('replyTime', models.DateTimeField(auto_now_add=True, verbose_name='回复时间')),
                ('goodTime', models.IntegerField(verbose_name='点赞次数')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=1000, verbose_name='介绍')),
                ('userName', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('question', models.CharField(max_length=100, verbose_name='密保')),
                ('answer', models.CharField(max_length=100, verbose_name='密保答案')),
            ],
        ),
        migrations.AddField(
            model_name='replies',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo'),
        ),
        migrations.AddField(
            model_name='replies',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Passage'),
        ),
        migrations.AddField(
            model_name='passage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.UserInfo'),
        ),
    ]
