# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='badTimes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passage',
            name='changeTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='content',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='passage',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='goodTimes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passage',
            name='readTimes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passage',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='replies',
            name='goodTime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='replies',
            name='replyTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='describe',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
