# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20181101_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='loginTimes',
            field=models.IntegerField(default=0),
        ),
    ]
