# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_userinfo_logintimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='badTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passage',
            name='goodTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passage',
            name='readTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='replies',
            name='goodTime',
            field=models.IntegerField(default=0),
        ),
    ]
